export const baseConfig = {
  GRADES_LABEL: "Calificaciones",
  HISTORIC_GRADES: "Calificaciones históricas",
  GRADES_SCALES: "Escala de notas",
  DROPOUT_PREDICTION: "Predicción de abandono",
  DROPOUT_PREDICTION_DESCRIPTION:
    "El sistema estima una probabilidad de abandono de",
  DROPOUT_PREDICTION_ACCURACY: "acierto del modelo:",
  SEMESTRAL_GRADE_COLOR: "rgb(70,130,180)",
  CUMULATED_GRADE_COLOR: "rgb(173,66,244)",
  PROGRAM_GRADE_COLOR: "rgb(102,102,102)",
  STATE_PASSED_LABEL_MINI: "AP",
  STATE_FAILED_LABEL_MINI: "RE",
  STATE_CANCELED_LABEL_MINI: "AN",
  STATE_PENDING_LABEL_MINI: "PEN",
  STATE_CURRENT_LABEL_MINI: "CUR",
  SEARCH_BUTTON_LABEL: "Buscar",
  LOGOUT_BUTTON_LABEL: "Salir",
  SEMESTRAL_GRADE_LABEL: "PSP",
  CUMULATED_GRADE_LABEL: "PGA",
  PROGRAM_GRADE_LABEL: "PGA de carrera",
  FLOW_CIRCLE_COLOR: "rgb(245,101,101)",
  FLOW_CIRCLE_LABEL: "Fluj",
  REQ_CIRCLE_LABEL: "Req",
  REQ_CIRCLE_COLOR: "rgb(66,153,225)",
  ACTIVE_COURSE_BOX_COLOR: "gray.500",
  FLOW_COURSE_BOX_COLOR: "red.400",
  REQUISITE_COURSE_BOX_COLOR: "blue.400",
  EXPLICIT_SEMESTER_COURSE_BOX_COLOR: "yellow.400",
  INACTIVE_COURSE_BOX_COLOR: "gray.400",
  MIN_PASS_SCALE_COLOR: "#b0ffa1",
  MAX_PASS_SCALE_COLOR: "#5bff3b",
  MIN_FAIL_SCALE_COLOR: "#ff4040",
  MAX_FAIL_SCALE_COLOR: "#ff8282",
  STATE_COURSE_CURRENT_COLOR: "blue",
  STATE_COURSE_CANCELED_COLOR: "white",
  STATE_COURSE_PENDING_COLOR: "blue.300",
  STATE_COURSE_CIRCLE_STROKE: "white",
  COURSE_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  COURSE_BOX_TEXT_COLOR: "black",
  DROPOUT_BACKGROUND_COLOR: "rgb(252,249,165)",
  DROPOUT_TEXT_COLOR: "black",
  HISTOGRAM_BAR_ACTIVE: "rgb(122,122,122)",
  HISTOGRAM_BAR_INACTIVE: "rgb(191,191,191)",
  SEARCH_BAR_BACKGROUND_COLOR: "rgb(52,58,64)",
  TAKEN_SEMESTER_BOX_ACTIVE: "yellow.400",
  TAKEN_SEMESTER_BOX_INACTIVE: "grey",
  TAKEN_SEMESTER_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  TAKEN_SEMESTER_BOX_TEXT_COLOR: "black",
  SEMESTER_HEADER_TEXT_COLOR: "rgb(70,130,180)",
  TIMELINE_TOOLTIP_TEXT_COLOR: "rgb(255,255,255)",
  TIMELINE_EXPLICIT_CIRCLE_COLOR: "rgb(236,201,75)",
  TIMELINE_AXIS_COLOR: "black",
  TIMELINE_AXIS_TEXT_COLOR: "black",
  TIMELINE_PASS_LINE_COLOR: "black",
  PASS_GRADE: 4,
  MIN_GRADE: 1,
  MAX_GRADE: 7,
  NO_CURRICULUMS_LABEL: "Sin planes",
  PROGRAM_NOT_SPECIFIED_PLACEHOLDER: "Programa no especificado",
  CURRICULUM_LABEL: "Plan",
  STUDENT_LABEL: "Estudiante",
  PLACEHOLDER_SEARCH_STUDENT: "ID del estudiante",
  STUDENT_LIST_TITLE: "Lista de estudiantes",
  ENTRY_YEAR_LABEL: "Ingreso",
  PROGRESS_LABEL: "Progreso",
  RISK_LABEL: "Riesgo",
  RISK_HIGH_THRESHOLD: 80,
  RISK_HIGH_COLOR: "rgb(255,0,0)",
  RISK_MEDIUM_THRESHOLD: 50,
  RISK_MEDIUM_COLOR: "rgb(252,186,3)",
  RISK_LOW_COLOR: "rgb(128,255,0)",
  LOGIN_WRONG_INFO_MESSAGE:
    "Información ingresada erronea. Verificar datos o su cuenta puede ser bloqueda por seguridad.",
  LOGIN_LOCKED_USER_MESSAGE:
    "Usuario bloqueado. Por favor revisar correo para recuperar su cuenta.",
  LOGIN_PUT_VALID_EMAIL: "Ingrese un Email Válido",
  LOGIN_PUT_VALID_PASSWORD_LENGTH: "Ingrese una contraseña de largo válido",
  LOGIN_EMAIL_LABEL: "Correo Electrónico",
  LOGIN_EMAIL_PLACEHOLDER: "email@uach.cl",
  LOGIN_PASSWORD_LABEL: "Contraseña",
  LOGIN_PASSWORD_PLACEHOLDER: "contraseña",
  LOGIN_REMEMBER_SESSION: "Mantenerse conectado",
  LOGIN_BUTTON: "Ingresar",
  LOGIN_ERROR_TITLE: "Error!",
  UNLOCK_LENGTH_VALIDATION:
    "El largo de la contraseña tiene que ser de al menos 8 caracteres y máximo de 100 caracteres.",
  UNLOCK_SPECIAL_SYMBOL_VALIDATION: `La contraseña debe contener al menos un caracter especial (~¡!$&+,:;=¿?@#|'<>.^*(){}"%-_).`,
  UNLOCK_LOWERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra minúscula.",
  UNLOCK_UPPERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra mayúscula.",
  UNLOCK_NUMBER_VALIDATION: "La contraseña debe contener al menos un número.",
  UNLOCK_REPEAT_VALIDATION: "Debe repetir su contraseña correctamente.",
  UNLOCK_NEW_PASSWORD_LABEL: "Nueva contraseña",
  UNLOCK_NEW_PASSWORD_PLACEHOLDER: "contraseña",
  UNLOCK_NEW_PASSWORD_REPEAT_LABEL: "Repita su contraseña",
  UNLOCK_ACTIVE_ACCOUNT_LABEL: "Activar cuenta",
  UNLOCK_ERROR_TITLE: "Error!",
  UNLOCK_WRONG_INFO_MESSAGE:
    "Usuario ingresado no está bloqueado o el código ingresado es erróneo.",
  UNLOCK_USER_OLD_PASSWORD_MESSAGE:
    "No puede ingresar una contraseña usada anteriormente.",
  ERROR_STUDENT_NOT_FOUND_MESSAGE:
    "Estudiante especificado no pudo ser encontrado en el programa especificado.",
  ERROR_PROGRAM_UNAUTHORIZED_MESSAGE:
    "No está autorizado para ver el programa especificado",
  ERROR_PROGRAM_NOT_FOUND: "Programa especificado no pudo ser encontrado.",
  CHECK_STUDENT_FROM_LIST_LABEL: "Ver estudiante",
};
