export const baseConfig = {
  ACTIVE_COURSE_BOX_COLOR: "gray.500",
  CANCELED_HISTORIC_TOOLTIP_LABEL: "Anulada",
  CHECK_STUDENT_FROM_LIST_LABEL: "Ver estudiante",
  COURSE_BOX_ALL_TRANSITION_DURATION: "all 0.3s",
  COURSE_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  COURSE_BOX_BORDER_WIDTH_ACTIVE: "2px",
  COURSE_BOX_BORDER_WIDTH_INACTIVE: "1px",
  COURSE_BOX_TEXT_COLOR: "black",
  CREDITS_LABEL: "Créditos",
  CUMULATED_GRADE_COLOR: "rgb(173,66,244)",
  CUMULATED_GRADE_LABEL: "PGA",
  CURRICULUM_LABEL: "Plan",
  DROPOUT_BACKGROUND_COLOR: "rgb(252,249,165)",
  DROPOUT_PREDICTION: "Predicción de abandono",
  DROPOUT_PREDICTION_ACCURACY: "acierto del modelo:",
  DROPOUT_PREDICTION_DESCRIPTION:
    "El sistema estima una probabilidad de abandono de",
  DROPOUT_TEXT_COLOR: "black",
  ENTRY_YEAR_LABEL: "Ingreso",
  ERROR_PROGRAM_NOT_FOUND: "Programa especificado no pudo ser encontrado.",
  ERROR_PROGRAM_UNAUTHORIZED_MESSAGE:
    "No está autorizado para ver el programa especificado",
  ERROR_STUDENT_NOT_FOUND_MESSAGE:
    "Estudiante especificado no pudo ser encontrado en el programa especificado.",
  EXPLICIT_SEMESTER_COURSE_BOX_COLOR: "yellow.400",
  FAIL_RATE_COLOR_SCALE_NEGATIVE_MAX_COLOR: "rgb(255,0,0)",
  FAIL_RATE_COLOR_SCALE_NEGATIVE_MIN_COLOR: "rgb(245,132,66)",
  FAIL_RATE_COLOR_SCALE_POSITIVE_MAX_COLOR: "#5bff3b",
  FAIL_RATE_COLOR_SCALE_POSITIVE_MIN_COLOR: "#b0ffa1",
  FLOW_CIRCLE_COLOR: "rgb(245,101,101)",
  FLOW_CIRCLE_LABEL: "Fluj",
  FLOW_COURSE_BOX_COLOR: "red.400",
  FOREPLAN_MODE_SWITCH_ACTIVE_BACKGROUND_COLOR: "blue.500",
  FOREPLAN_MODE_SWITCH_ACTIVE_TEXT_COLOR: "white",
  FOREPLAN_MODE_SWITCH_FONT_FAMILY: "Lato",
  FOREPLAN_MODE_SWITCH_FONT_SIZE: "1.2em",
  FOREPLAN_MODE_SWITCH_HEIGHT: "3em",
  FOREPLAN_MODE_SWITCH_INACTIVE_BACKGROUND_COLOR: "gray.500",
  FOREPLAN_MODE_SWITCH_INACTIVE_TEXT_COLOR: "white",
  FOREPLAN_MODE_SWITCH_LABEL: "Plan Próximo Semestre",
  FOREPLAN_SUMMARY_ADVICE_PARAGRAPH_FONT_SIZE: "1.2em",
  FOREPLAN_SUMMARY_ADVICE_TITLE_FONT_SIZE: "2em",
  FOREPLAN_SUMMARY_ADVICE_FAIL_RATES_COLORS: {
    high: "#ffab91",
    mid: "#fed976",
    low: "#a1d99b",
  },
  FOREPLAN_SUMMARY_BADGE_COURSE_CREDITS_WIDTH: [
    {
      min: 0,
      max: 0,
      width: "7.9em",
    },
    {
      min: 1,
      max: 2,
      width: "8.5em",
    },
    {
      min: 3,
      max: 4,
      width: "9em",
    },
    {
      min: 5,
      max: 6,
      width: "9.5em",
    },
    {
      min: 7,
      max: 12,
      width: "10em",
    },
    {
      min: 13,
      max: 999,
      width: "10.5em",
    },
  ] as { min: number; max: number; width: string }[],
  FOREPLAN_SUMMARY_BACKGROUND_COLOR: "#333333",
  FOREPLAN_SUMMARY_BORDER_RADIUS: "10px",
  FOREPLAN_SUMMARY_FONT_COLOR: "white",
  FOREPLAN_SUMMARY_BADGE_FONT_SIZE: "1em",
  FOREPLAN_SUMMARY_HEIGHT: "23em",
  FOREPLAN_SUMMARY_MOBILE_BREAKPOINT_HEIGHT: 1080,
  FOREPLAN_SUMMARY_POSITION_MOBILE_BREAKPOINT_WIDTH: 1920,
  FOREPLAN_SUMMARY_TAB_COLOR: "#888",
  FOREPLAN_SUMMARY_TAB_ICON_SIZE: "1.3em",
  FOREPLAN_SUMMARY_TAB_NUMBER_FONT_SIZE: {
    oneDigit: "1.2em",
    twoDigits: "1.5em",
  },
  FOREPLAN_SUMMARY_TAB_WIDTH: "2em",
  FOREPLAN_SUMMARY_TITLE_FONT_SIZE: "1.5em",
  FOREPLAN_SUMMARY_TITLE_LABEL: "Plan semestre 1 2020",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_LABEL: "Créditos totales",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_LABEL_FONT_SIZE: "1.2em",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NUMBER_SIZE: "1.5em",
  FOREPLAN_SUMMARY_WAFFLE_COLORS_FAIL_RATE: {
    high: "#ffab91",
    mid: "#fed976",
    low: "#a1d99b",
  },
  FOREPLAN_SUMMARY_WAFFLE_RECT_SEPARATION: 1.2,
  FOREPLAN_SUMMARY_WAFFLE_SIZE: 100,
  FOREPLAN_SUMMARY_WAFFLE_SQUARE_SIZE: 8,
  FOREPLAN_SUMMARY_WAFFLE_TRANSLATE_X: 4,
  FOREPLAN_SUMMARY_WAFFLE_TRANSLATE_Y: 4,
  GRADES_LABEL: "Calificaciones",
  GRADES_SCALES: "Escala de notas",
  HISTOGRAM_BAR_ACTIVE: "rgb(122,122,122)",
  HISTOGRAM_BAR_INACTIVE: "rgb(191,191,191)",
  HISTORIC_GRADES: "Calificaciones históricas",
  INACTIVE_COURSE_BOX_COLOR: "gray.400",
  LOGIN_BUTTON: "Ingresar",
  LOGIN_EMAIL_LABEL: "Correo Electrónico",
  LOGIN_EMAIL_PLACEHOLDER: "email@uach.cl",
  LOGIN_ERROR_TITLE: "Error!",
  LOGIN_LOCKED_USER_MESSAGE:
    "Usuario bloqueado. Por favor revisar correo para recuperar su cuenta.",
  LOGIN_PASSWORD_LABEL: "Contraseña",
  LOGIN_PASSWORD_PLACEHOLDER: "contraseña",
  LOGIN_PUT_VALID_EMAIL: "Ingrese un Email Válido",
  LOGIN_PUT_VALID_PASSWORD_LENGTH: "Ingrese una contraseña de largo válido",
  LOGIN_REMEMBER_SESSION: "Mantenerse conectado",
  LOGIN_WRONG_INFO_MESSAGE:
    "Información ingresada erronea. Verificar datos o su cuenta puede ser bloqueda por seguridad.",
  LOGOUT_BUTTON_LABEL: "Salir",
  MAX_FAIL_SCALE_COLOR: "#ff8282",
  MAX_GRADE: 7,
  MAX_PASS_SCALE_COLOR: "#5bff3b",
  MIN_FAIL_SCALE_COLOR: "#ff4040",
  MIN_GRADE: 1,
  MIN_PASS_SCALE_COLOR: "#b0ffa1",
  NO_CURRICULUMS_LABEL: "Sin planes",
  NO_HISTORIC_DATA: "No hay datos a mostrar",
  PARALLEL_GROUP_BACKGROUND_COLOR: "#ddd",
  PARALLEL_GROUP_LABEL: "GP",
  PARALLEL_GROUP_LABEL_COLOR: "black",
  PASS_GRADE: 4,
  PLACEHOLDER_SEARCH_STUDENT: "ID del estudiante",
  PROGRAM_GRADE_COLOR: "rgb(102,102,102)",
  PROGRAM_GRADE_LABEL: "PGA de carrera",
  PROGRAM_NOT_SPECIFIED_PLACEHOLDER: "Programa no especificado",
  PROGRESS_LABEL: "Progreso",
  REQ_CIRCLE_COLOR: "rgb(66,153,225)",
  REQ_CIRCLE_LABEL: "Req",
  REQUISITE_COURSE_BOX_COLOR: "blue.400",
  RISK_HIGH_COLOR: "rgb(255,0,0)",
  RISK_HIGH_THRESHOLD: 80,
  RISK_LABEL: "Riesgo",
  RISK_LOW_COLOR: "rgb(128,255,0)",
  RISK_MEDIUM_COLOR: "rgb(252,186,3)",
  RISK_MEDIUM_THRESHOLD: 50,
  SEARCH_BAR_BACKGROUND_COLOR: "rgb(52,58,64)",
  SEARCH_BUTTON_LABEL: "Buscar",
  SEMESTER_HEADER_FONT_SIZE: "1.5em",
  SEMESTER_HEADER_TEXT_COLOR: "rgb(70,130,180)",
  SEMESTRAL_GRADE_COLOR: "rgb(70,130,180)",
  SEMESTRAL_GRADE_LABEL: "PSP",
  STATE_CANCELED_LABEL_MINI: "An",
  STATE_COLOR_FAIL_FALLBACK: "rgb(214,96,77)",
  STATE_COLOR_PASS_FALLBACK: "rgb(102,180,62)",
  STATE_COURSE_CANCELED_COLOR: "white",
  STATE_COURSE_CIRCLE_STROKE: "white",
  STATE_COURSE_CURRENT_COLOR: "blue.500",
  STATE_COURSE_PENDING_COLOR: "blue.300",
  STATE_CURRENT_LABEL_MINI: "Reg",
  STATE_FAILED_LABEL_MINI: "Rep",
  STATE_PASSED_LABEL_MINI: "Apr",
  STATE_PENDING_LABEL_MINI: "Pen",
  STUDENT_LABEL: "Estudiante",
  STUDENT_LIST_TITLE: "Lista de estudiantes",
  TAKEN_SEMESTER_BOX_ACTIVE: "yellow.400",
  TAKEN_SEMESTER_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  TAKEN_SEMESTER_BOX_BORDER: "3px solid",
  TAKEN_SEMESTER_BOX_BORDER_RADIUS: "8px",
  TAKEN_SEMESTER_BOX_FONT_SIZE: "1.2em",
  TAKEN_SEMESTER_BOX_HEIGHT: "3em",
  TAKEN_SEMESTER_BOX_INACTIVE: "grey",
  TAKEN_SEMESTER_BOX_MARGIN_SIDES: 3,
  TAKEN_SEMESTER_BOX_PADDING: "6px",
  TAKEN_SEMESTER_BOX_TEXT_COLOR: "black",
  TAKEN_SEMESTER_BOX_TRANSITION: "all 0.4s ease-in-out",
  TIMELINE_AXIS_COLOR: "black",
  TIMELINE_AXIS_TEXT_COLOR: "black",
  TIMELINE_EXPLICIT_CIRCLE_COLOR: "rgb(236,201,75)",
  TIMELINE_PASS_LINE_COLOR: "black",
  TIMELINE_TOOLTIP_TEXT_COLOR: "rgb(255,255,255)",
  UNLOCK_ACTIVE_ACCOUNT_LABEL: "Activar cuenta",
  UNLOCK_ERROR_TITLE: "Error!",
  UNLOCK_LENGTH_VALIDATION:
    "El largo de la contraseña tiene que ser de al menos 8 caracteres y máximo de 100 caracteres.",
  UNLOCK_LOWERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra minúscula.",
  UNLOCK_NEW_PASSWORD_LABEL: "Nueva contraseña",
  UNLOCK_NEW_PASSWORD_PLACEHOLDER: "contraseña",
  UNLOCK_NEW_PASSWORD_REPEAT_LABEL: "Repita su contraseña",
  UNLOCK_NUMBER_VALIDATION: "La contraseña debe contener al menos un número.",
  UNLOCK_REPEAT_VALIDATION: "Debe repetir su contraseña correctamente.",
  UNLOCK_SPECIAL_SYMBOL_VALIDATION:
    "La contraseña debe contener al menos un caracter especial (~¡!$&+,:;=¿?@#|'<>.^*(){}\"%-_).",
  UNLOCK_UPPERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra mayúscula.",
  UNLOCK_USER_OLD_PASSWORD_MESSAGE:
    "No puede ingresar una contraseña usada anteriormente.",
  UNLOCK_WRONG_INFO_MESSAGE:
    "Usuario ingresado no está bloqueado o el código ingresado es erróneo.",
};

export const baseConfigAdmin: typeof baseConfig &
  Record<string, any> = baseConfig;
