import { StateCourse } from "../";
import { ICourse } from "../../interfaces";

const semesters: { semester: ICourse[] }[] = [
  {
    semester: [
      {
        name: "ALGEBRA PARA INGENIERIA",
        code: "BAIN017-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["BAIN036-07", "BAIN038-07", "INFO025-08", "BAIN037-07"],
        requisites: [],
        historicDistribution: [
          { value: 892, min: 1, max: 2 },
          { value: 1047, min: 2, max: 3 },
          { value: 1106, min: 3, max: 4 },
          { value: 2305, min: 4, max: 5 },
          { value: 531, min: 5, max: 6 },
          { value: 98, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "CURSADA",
            grade: 2,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 51, min: 1, max: 2 },
              { value: 88, min: 2, max: 3 },
              { value: 82, min: 3, max: 4 },
              { value: 135, min: 4, max: 5 },
              { value: 29, min: 5, max: 6 },
              { value: 12, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 2.7,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 23, min: 1, max: 2 },
              { value: 31, min: 2, max: 3 },
              { value: 34, min: 3, max: 4 },
              { value: 42, min: 4, max: 5 },
              { value: 2, min: 5, max: 6 },
              { value: 1, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 2.6,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 24, min: 1, max: 2 },
              { value: 50, min: 2, max: 3 },
              { value: 90, min: 3, max: 4 },
              { value: 116, min: 4, max: 5 },
              { value: 48, min: 5, max: 6 },
              { value: 18, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "QUIMICA PARA INGENIERIA",
        code: "BAIN019-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO184-08"],
        requisites: [],
        historicDistribution: [
          { value: 444, min: 1, max: 2 },
          { value: 404, min: 2, max: 3 },
          { value: 710, min: 3, max: 4 },
          { value: 2234, min: 4, max: 5 },
          { value: 957, min: 5, max: 6 },
          { value: 253, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 3.8,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 8, min: 1, max: 2 },
              { value: 5, min: 2, max: 3 },
              { value: 28, min: 3, max: 4 },
              { value: 73, min: 4, max: 5 },
              { value: 28, min: 5, max: 6 },
              { value: 4, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3.7,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 81, min: 1, max: 2 },
              { value: 62, min: 2, max: 3 },
              { value: 43, min: 3, max: 4 },
              { value: 95, min: 4, max: 5 },
              { value: 50, min: 5, max: 6 },
              { value: 16, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "EDUCACIÓN FÍSICA Y SALUD",
        code: "DYRE060-90",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 0, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 1, min: 4, max: 5 },
          { value: 2, min: 5, max: 6 },
          { value: 64, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 0,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 0, min: 1, max: 2 },
              { value: 0, min: 2, max: 3 },
              { value: 0, min: 3, max: 4 },
              { value: 1, min: 4, max: 5 },
              { value: 1, min: 5, max: 6 },
              { value: 21, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "INTRODUCCION A LA PROGRAMACION",
        code: "INFO013-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO023-08", "INFO043-07"],
        requisites: [],
        historicDistribution: [
          { value: 97, min: 1, max: 2 },
          { value: 97, min: 2, max: 3 },
          { value: 109, min: 3, max: 4 },
          { value: 338, min: 4, max: 5 },
          { value: 114, min: 5, max: 6 },
          { value: 31, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 4.3,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 1, min: 1, max: 2 },
              { value: 1, min: 2, max: 3 },
              { value: 1, min: 3, max: 4 },
              { value: 9, min: 4, max: 5 },
              { value: 1, min: 5, max: 6 },
              { value: 0, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3.3,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 1, min: 1, max: 2 },
              { value: 3, min: 2, max: 3 },
              { value: 12, min: 3, max: 4 },
              { value: 38, min: 4, max: 5 },
              { value: 4, min: 5, max: 6 },
              { value: 4, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "TALLER DE INGENIERIA I",
        code: "INFO015-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO025-08"],
        requisites: [],
        historicDistribution: [
          { value: 21, min: 1, max: 2 },
          { value: 11, min: 2, max: 3 },
          { value: 32, min: 3, max: 4 },
          { value: 226, min: 4, max: 5 },
          { value: 205, min: 5, max: 6 },
          { value: 109, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 4.4,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 2, min: 1, max: 2 },
              { value: 0, min: 2, max: 3 },
              { value: 4, min: 3, max: 4 },
              { value: 17, min: 4, max: 5 },
              { value: 17, min: 5, max: 6 },
              { value: 23, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "COMUNICACION: IDIOMA ESPAÑOL",
        code: "BAIN009-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["ADMI100-90"],
        requisites: [],
        historicDistribution: [
          { value: 188, min: 1, max: 2 },
          { value: 73, min: 2, max: 3 },
          { value: 55, min: 3, max: 4 },
          { value: 669, min: 4, max: 5 },
          { value: 1940, min: 5, max: 6 },
          { value: 1209, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 6,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 11, min: 1, max: 2 },
              { value: 5, min: 2, max: 3 },
              { value: 2, min: 3, max: 4 },
              { value: 28, min: 4, max: 5 },
              { value: 183, min: 5, max: 6 },
              { value: 119, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "GEOMETRIA PARA INGENIERIA",
        code: "BAIN012-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["BAIN038-07", "INFO025-08"],
        requisites: [],
        historicDistribution: [
          { value: 1235, min: 1, max: 2 },
          { value: 1010, min: 2, max: 3 },
          { value: 1026, min: 3, max: 4 },
          { value: 2130, min: 4, max: 5 },
          { value: 589, min: 5, max: 6 },
          { value: 132, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "CURSADA",
            grade: 1.8,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 47, min: 1, max: 2 },
              { value: 64, min: 2, max: 3 },
              { value: 95, min: 3, max: 4 },
              { value: 171, min: 4, max: 5 },
              { value: 46, min: 5, max: 6 },
              { value: 11, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 2.2,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 21, min: 1, max: 2 },
              { value: 44, min: 2, max: 3 },
              { value: 25, min: 3, max: 4 },
              { value: 56, min: 4, max: 5 },
              { value: 6, min: 5, max: 6 },
              { value: 0, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 41, min: 1, max: 2 },
              { value: 91, min: 2, max: 3 },
              { value: 81, min: 3, max: 4 },
              { value: 90, min: 4, max: 5 },
              { value: 31, min: 5, max: 6 },
              { value: 7, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
    ],
  },
  {
    semester: [
      {
        name: "ALGEBRA LINEAL PARA INGENIERIA",
        code: "BAIN036-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO043-07", "BAIN052-07", "INFO172-00"],
        requisites: ["BAIN017-07"],
        historicDistribution: [
          { value: 518, min: 1, max: 2 },
          { value: 731, min: 2, max: 3 },
          { value: 738, min: 3, max: 4 },
          { value: 1823, min: 4, max: 5 },
          { value: 308, min: 5, max: 6 },
          { value: 69, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "FISICA I PARA INGENIERIA",
        code: "BAIN038-07",
        credits: [{ label: "SCT", value: 8 }],
        flow: ["BAIN043-07", "INFO184-08"],
        requisites: ["BAIN012-07", "BAIN017-07"],
        historicDistribution: [
          { value: 468, min: 1, max: 2 },
          { value: 657, min: 2, max: 3 },
          { value: 887, min: 3, max: 4 },
          { value: 2033, min: 4, max: 5 },
          { value: 178, min: 5, max: 6 },
          { value: 17, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "COMUNICACION: IDIOMA INGLES",
        code: "BAIN039-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 316, min: 1, max: 2 },
          { value: 156, min: 2, max: 3 },
          { value: 316, min: 3, max: 4 },
          { value: 1608, min: 4, max: 5 },
          { value: 925, min: 5, max: 6 },
          { value: 486, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 4,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 6, min: 1, max: 2 },
              { value: 6, min: 2, max: 3 },
              { value: 24, min: 3, max: 4 },
              { value: 65, min: 4, max: 5 },
              { value: 63, min: 5, max: 6 },
              { value: 30, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "PROGRAMACION",
        code: "INFO023-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO033-07"],
        requisites: ["INFO013-07"],
        historicDistribution: [
          { value: 62, min: 1, max: 2 },
          { value: 61, min: 2, max: 3 },
          { value: 48, min: 3, max: 4 },
          { value: 278, min: 4, max: 5 },
          { value: 74, min: 5, max: 6 },
          { value: 32, min: 6, max: 7 },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "ANULADA",
            grade: 0,
            state: StateCourse.Canceled,
            currentDistribution: [
              { value: 3, min: 1, max: 2 },
              { value: 0, min: 2, max: 3 },
              { value: 1, min: 3, max: 4 },
              { value: 17, min: 4, max: 5 },
              { value: 5, min: 5, max: 6 },
              { value: 1, min: 6, max: 7 },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "TALLER DE INGENIERIA II",
        code: "INFO025-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO035-08"],
        requisites: ["BAIN012-07", "BAIN017-07", "INFO015-08"],
        historicDistribution: [
          { value: 12, min: 1, max: 2 },
          { value: 3, min: 2, max: 3 },
          { value: 5, min: 3, max: 4 },
          { value: 83, min: 4, max: 5 },
          { value: 174, min: 5, max: 6 },
          { value: 110, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "CALCULO I PARA INGENIERIA",
        code: "BAIN037-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["BAIN041-07", "BAIN043-07", "BAIN042-07", "INFO184-08"],
        requisites: ["BAIN017-07"],
        historicDistribution: [
          { value: 611, min: 1, max: 2 },
          { value: 937, min: 2, max: 3 },
          { value: 989, min: 3, max: 4 },
          { value: 1889, min: 4, max: 5 },
          { value: 258, min: 5, max: 6 },
          { value: 30, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ECUACIONES DIFERENCIALES PARA INGENIERIA",
        code: "BAIN041-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["BAIN054-07", "INFO045-08", "BAIN053-07", "INFO183-00"],
        requisites: ["BAIN037-07"],
        historicDistribution: [
          { value: 294, min: 1, max: 2 },
          { value: 392, min: 2, max: 3 },
          { value: 550, min: 3, max: 4 },
          { value: 1457, min: 4, max: 5 },
          { value: 209, min: 5, max: 6 },
          { value: 30, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "FISICA II PARA INGENIERIA",
        code: "BAIN043-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN037-07", "BAIN038-07"],
        historicDistribution: [
          { value: 111, min: 1, max: 2 },
          { value: 190, min: 2, max: 3 },
          { value: 563, min: 3, max: 4 },
          { value: 1603, min: 4, max: 5 },
          { value: 149, min: 5, max: 6 },
          { value: 16, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "PROGRAMACION ORIENTADA A OBJETOS",
        code: "INFO033-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO023-08"],
        historicDistribution: [
          { value: 34, min: 1, max: 2 },
          { value: 20, min: 2, max: 3 },
          { value: 35, min: 3, max: 4 },
          { value: 184, min: 4, max: 5 },
          { value: 81, min: 5, max: 6 },
          { value: 56, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TALLER DE INGENIERIA III",
        code: "INFO035-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: [
          "INFO045-08",
          "INFO053-07",
          "ADMI100-90",
          "INFO175-08",
          "INFO265-08",
          "IECO102-05",
          "INFO264-00",
        ],
        requisites: ["INFO025-08"],
        historicDistribution: [
          { value: 2, min: 1, max: 2 },
          { value: 3, min: 2, max: 3 },
          { value: 9, min: 3, max: 4 },
          { value: 80, min: 4, max: 5 },
          { value: 177, min: 5, max: 6 },
          { value: 36, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ESTRUCTURAS DISCRETAS",
        code: "INFO043-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO053-07"],
        requisites: ["BAIN036-07", "INFO013-07"],
        historicDistribution: [
          { value: 25, min: 1, max: 2 },
          { value: 27, min: 2, max: 3 },
          { value: 70, min: 3, max: 4 },
          { value: 208, min: 4, max: 5 },
          { value: 41, min: 5, max: 6 },
          { value: 6, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "CALCULO II PARA INGENIERIA",
        code: "BAIN042-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: [
          "BAIN054-07",
          "INFO045-08",
          "INFO173-00",
          "IECO102-05",
          "INFO185-97",
        ],
        requisites: ["BAIN037-07"],
        historicDistribution: [
          { value: 397, min: 1, max: 2 },
          { value: 648, min: 2, max: 3 },
          { value: 625, min: 3, max: 4 },
          { value: 1395, min: 4, max: 5 },
          { value: 148, min: 5, max: 6 },
          { value: 27, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ESTADISTICA Y PROBABILIDADES PARA INGENIERIA",
        code: "BAIN052-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO173-00", "INFO185-97"],
        requisites: ["BAIN036-07"],
        historicDistribution: [
          { value: 284, min: 1, max: 2 },
          { value: 174, min: 2, max: 3 },
          { value: 186, min: 3, max: 4 },
          { value: 1306, min: 4, max: 5 },
          { value: 300, min: 5, max: 6 },
          { value: 62, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "FISICA III PARA INGENIERIA",
        code: "BAIN054-07",
        credits: [{ label: "SCT", value: 8 }],
        flow: ["INFO284-08"],
        requisites: ["BAIN041-07", "BAIN042-07"],
        historicDistribution: [
          { value: 54, min: 1, max: 2 },
          { value: 79, min: 2, max: 3 },
          { value: 238, min: 3, max: 4 },
          { value: 1233, min: 4, max: 5 },
          { value: 169, min: 5, max: 6 },
          { value: 12, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO 1",
        code: "ELECT01",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "TALLER",
        code: "INFO045-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN041-07", "BAIN042-07", "INFO035-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 30, min: 4, max: 5 },
          { value: 96, min: 5, max: 6 },
          { value: 114, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ESTRUCTURAS DE DATOS Y ALGORITMOS",
        code: "INFO053-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO164-00", "INFO175-08", "INFO265-08", "INFO163-08"],
        requisites: ["INFO035-08", "INFO043-07"],
        historicDistribution: [
          { value: 27, min: 1, max: 2 },
          { value: 42, min: 2, max: 3 },
          { value: 76, min: 3, max: 4 },
          { value: 153, min: 4, max: 5 },
          { value: 59, min: 5, max: 6 },
          { value: 6, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "METODOS NUMERICOS PARA INGENIERIA",
        code: "BAIN053-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN041-07"],
        historicDistribution: [
          { value: 158, min: 1, max: 2 },
          { value: 307, min: 2, max: 3 },
          { value: 498, min: 3, max: 4 },
          { value: 1195, min: 4, max: 5 },
          { value: 149, min: 5, max: 6 },
          { value: 15, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ADMINISTRACION DE EMPRESAS",
        code: "ADMI100-90",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO263-08", "INFO271-08", "INFO275-08", "INFO276-08"],
        requisites: ["BAIN009-07", "INFO035-08"],
        historicDistribution: [
          { value: 9, min: 1, max: 2 },
          { value: 9, min: 2, max: 3 },
          { value: 17, min: 3, max: 4 },
          { value: 246, min: 4, max: 5 },
          { value: 197, min: 5, max: 6 },
          { value: 71, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TEORIA DE AUTOMATAS",
        code: "INFO164-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO261-08", "INFO165-00", "INFO270-00"],
        requisites: ["INFO053-07"],
        historicDistribution: [
          { value: 4, min: 1, max: 2 },
          { value: 23, min: 2, max: 3 },
          { value: 31, min: 3, max: 4 },
          { value: 95, min: 4, max: 5 },
          { value: 63, min: 5, max: 6 },
          { value: 17, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "INVESTIGACION OPERATIVA I",
        code: "INFO172-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO173-00"],
        requisites: ["BAIN036-07"],
        historicDistribution: [
          { value: 20, min: 1, max: 2 },
          { value: 18, min: 2, max: 3 },
          { value: 27, min: 3, max: 4 },
          { value: 106, min: 4, max: 5 },
          { value: 74, min: 5, max: 6 },
          { value: 32, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TALLER DE CONSTRUCCION DE SOFTWARE",
        code: "INFO175-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO263-08", "INFO284-08", "INFO267-00"],
        requisites: ["INFO035-08", "INFO053-07"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 5, min: 3, max: 4 },
          { value: 37, min: 4, max: 5 },
          { value: 90, min: 5, max: 6 },
          { value: 69, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ARQUITECTURA DE COMPUTADORES",
        code: "INFO184-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO183-00", "INFO185-97"],
        requisites: ["BAIN019-07", "BAIN037-07", "BAIN038-07"],
        historicDistribution: [
          { value: 17, min: 1, max: 2 },
          { value: 23, min: 2, max: 3 },
          { value: 33, min: 3, max: 4 },
          { value: 122, min: 4, max: 5 },
          { value: 62, min: 5, max: 6 },
          { value: 12, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "COMPUTACION GRAFICA",
        code: "INFO265-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["INFO035-08", "INFO053-07"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 4, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 62, min: 4, max: 5 },
          { value: 94, min: 5, max: 6 },
          { value: 33, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "BASES DE DATOS",
        code: "INFO261-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO264-00"],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 7, min: 2, max: 3 },
          { value: 20, min: 3, max: 4 },
          { value: 81, min: 4, max: 5 },
          { value: 78, min: 5, max: 6 },
          { value: 21, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ANALISIS DE SISTEMAS LINEALES",
        code: "INFO183-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO189-08", "INFO284-08"],
        requisites: ["BAIN041-07", "INFO184-08"],
        historicDistribution: [
          { value: 12, min: 1, max: 2 },
          { value: 21, min: 2, max: 3 },
          { value: 31, min: 3, max: 4 },
          { value: 121, min: 4, max: 5 },
          { value: 42, min: 5, max: 6 },
          { value: 8, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "INVESTIGACION OPERATIVA II",
        code: "INFO173-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO272-00", "INFO273-00", "INFO274-00"],
        requisites: ["BAIN042-07", "BAIN052-07", "INFO172-00"],
        historicDistribution: [
          { value: 11, min: 1, max: 2 },
          { value: 7, min: 2, max: 3 },
          { value: 26, min: 3, max: 4 },
          { value: 97, min: 4, max: 5 },
          { value: 63, min: 5, max: 6 },
          { value: 20, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "COMPILADORES",
        code: "INFO165-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: [],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 3, min: 1, max: 2 },
          { value: 8, min: 2, max: 3 },
          { value: 35, min: 3, max: 4 },
          { value: 79, min: 4, max: 5 },
          { value: 62, min: 5, max: 6 },
          { value: 19, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "PROGRAMACION CONCURRENTE",
        code: "INFO163-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO182-00"],
        requisites: ["INFO053-07"],
        historicDistribution: [
          { value: 15, min: 1, max: 2 },
          { value: 6, min: 2, max: 3 },
          { value: 18, min: 3, max: 4 },
          { value: 97, min: 4, max: 5 },
          { value: 71, min: 5, max: 6 },
          { value: 14, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "SISTEMA OPERATIVO",
        code: "INFO182-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO281-08", "INFO273-00"],
        requisites: ["INFO163-08"],
        historicDistribution: [
          { value: 5, min: 1, max: 2 },
          { value: 14, min: 2, max: 3 },
          { value: 23, min: 3, max: 4 },
          { value: 96, min: 4, max: 5 },
          { value: 43, min: 5, max: 6 },
          { value: 11, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ECONOMIA GENERAL",
        code: "IECO102-05",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO271-08", "INFO272-00"],
        requisites: ["BAIN042-07", "INFO035-08"],
        historicDistribution: [
          { value: 52, min: 1, max: 2 },
          { value: 57, min: 2, max: 3 },
          { value: 57, min: 3, max: 4 },
          { value: 775, min: 4, max: 5 },
          { value: 365, min: 5, max: 6 },
          { value: 71, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "COMUNICACIONES",
        code: "INFO185-97",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO281-08"],
        requisites: ["BAIN042-07", "BAIN052-07", "INFO184-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 6, min: 3, max: 4 },
          { value: 95, min: 4, max: 5 },
          { value: 48, min: 5, max: 6 },
          { value: 7, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SOFTWARE DE INGENIERIA",
        code: "INFO189-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["EICI245-08"],
        requisites: ["BAIN043-07", "BAIN053-07", "INFO045-08", "INFO183-00"],
        historicDistribution: [
          { value: 12, min: 1, max: 2 },
          { value: 7, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 40, min: 4, max: 5 },
          { value: 69, min: 5, max: 6 },
          { value: 31, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "FUNDAMENTOS DE INGENIERIA DE SOFTWARE",
        code: "INFO263-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO266-08", "INFO264-00"],
        requisites: ["ADMI100-90", "INFO175-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 3, min: 2, max: 3 },
          { value: 10, min: 3, max: 4 },
          { value: 67, min: 4, max: 5 },
          { value: 65, min: 5, max: 6 },
          { value: 15, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "INGENIERIA DE SISTEMAS",
        code: "INFO270-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO271-08", "INFO275-08", "INFO276-08"],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 17, min: 3, max: 4 },
          { value: 63, min: 4, max: 5 },
          { value: 60, min: 5, max: 6 },
          { value: 14, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "INTERFAZ HUMANO - COMPUTADOR",
        code: "INFO266-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI297-90", "EICI245-08"],
        requisites: ["INFO263-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 4, min: 3, max: 4 },
          { value: 42, min: 4, max: 5 },
          { value: 88, min: 5, max: 6 },
          { value: 11, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TALLER INGENIERIA DE SOFTWARE",
        code: "INFO264-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: [
          "INFO268-00",
          "INFO251-08",
          "INFO252-97",
          "EICI297-90",
          "EICI245-08",
          "EICI246-08",
          "EICI247-08",
        ],
        requisites: ["INFO035-08", "INFO261-08", "INFO263-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 8, min: 4, max: 5 },
          { value: 40, min: 5, max: 6 },
          { value: 92, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE INFORMACION",
        code: "INFO271-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO252-97", "EICI297-90", "EICI246-08"],
        requisites: ["ADMI100-90", "IECO102-05", "INFO270-00"],
        historicDistribution: [
          { value: 3, min: 1, max: 2 },
          { value: 3, min: 2, max: 3 },
          { value: 6, min: 3, max: 4 },
          { value: 59, min: 4, max: 5 },
          { value: 77, min: 5, max: 6 },
          { value: 6, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "INGENIERIA ECONOMICA",
        code: "INFO272-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [
          "INFO251-08",
          "INFO252-97",
          "INFO275-08",
          "EICI297-90",
          "INFO276-08",
          "EICI247-08",
        ],
        requisites: ["IECO102-05", "INFO173-00"],
        historicDistribution: [
          { value: 5, min: 1, max: 2 },
          { value: 8, min: 2, max: 3 },
          { value: 11, min: 3, max: 4 },
          { value: 59, min: 4, max: 5 },
          { value: 70, min: 5, max: 6 },
          { value: 16, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "REDES",
        code: "INFO281-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [
          "INFO273-00",
          "INFO251-08",
          "EICI297-90",
          "EICI245-08",
          "EICI246-08",
          "EICI247-08",
        ],
        requisites: ["INFO182-00", "INFO185-97"],
        historicDistribution: [
          { value: 5, min: 1, max: 2 },
          { value: 7, min: 2, max: 3 },
          { value: 10, min: 3, max: 4 },
          { value: 112, min: 4, max: 5 },
          { value: 30, min: 5, max: 6 },
          { value: 2, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TALLER DE INTEGRACION DE TIC",
        code: "INFO284-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI297-90", "EICI245-08", "EICI246-08"],
        requisites: ["BAIN054-07", "INFO175-08", "INFO183-00"],
        historicDistribution: [
          { value: 2, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 9, min: 4, max: 5 },
          { value: 49, min: 5, max: 6 },
          { value: 86, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "TALLER DE BASE DE DATOS",
        code: "INFO268-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO264-00"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 35, min: 4, max: 5 },
          { value: 53, min: 5, max: 6 },
          { value: 34, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "EVALUACION DE DESEMPEÑO",
        code: "INFO273-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: [],
        requisites: ["INFO173-00", "INFO182-00", "INFO281-08"],
        historicDistribution: [
          { value: 0, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 22, min: 4, max: 5 },
          { value: 60, min: 5, max: 6 },
          { value: 34, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SEMINARIO DE ETICA PROFESIONAL",
        code: "INFO251-08",
        credits: [{ label: "SCT", value: 2 }],
        flow: [],
        requisites: ["INFO264-00", "INFO272-00", "INFO281-08"],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "PROYECTO I",
        code: "INFO252-97",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO264-00", "INFO271-08", "INFO272-00"],
        historicDistribution: [
          { value: 0, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 23, min: 4, max: 5 },
          { value: 67, min: 5, max: 6 },
          { value: 28, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE GESTION ESTRATEGICOS",
        code: "INFO275-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["EICI246-08"],
        requisites: ["ADMI100-90", "INFO270-00", "INFO272-00"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 56, min: 4, max: 5 },
          { value: 53, min: 5, max: 6 },
          { value: 6, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "INGLES FUNCIONAL",
        code: "CIDI108-02",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 2, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 29, min: 4, max: 5 },
          { value: 47, min: 5, max: 6 },
          { value: 44, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "PRACTICA PROFESIONAL",
        code: "EICI297-90",
        credits: [{ label: "SCT", value: 8 }],
        flow: [],
        requisites: [
          "INFO264-00",
          "INFO266-08",
          "INFO271-08",
          "INFO272-00",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 1",
        code: "ELECT20",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "INTELIGENCIA ARTIFICIAL",
        code: "INFO267-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["INFO175-08"],
        historicDistribution: [
          { value: 5, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 5, min: 3, max: 4 },
          { value: 34, min: 4, max: 5 },
          { value: 65, min: 5, max: 6 },
          { value: 16, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE GESTION TACTICOS",
        code: "INFO276-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["EICI261-08", "EICI255-08", "INFO253-08"],
        requisites: ["ADMI100-90", "INFO270-00", "INFO272-00"],
        historicDistribution: [
          { value: 0, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 18, min: 4, max: 5 },
          { value: 63, min: 5, max: 6 },
          { value: 34, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "TALLER DE SOFTWARE- PROYECTO INTEGRACIÓN DE TIC",
        code: "EICI245-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["EICI255-08", "INFO253-08"],
        requisites: [
          "INFO189-08",
          "INFO264-00",
          "INFO266-08",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 0, min: 4, max: 5 },
          { value: 4, min: 5, max: 6 },
          { value: 33, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "ARQUITECTURA DE SISTEMAS",
        code: "EICI246-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI261-08", "EICI255-08", "INFO253-08"],
        requisites: [
          "INFO264-00",
          "INFO271-08",
          "INFO275-08",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [
          { value: 2, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 3, min: 4, max: 5 },
          { value: 15, min: 5, max: 6 },
          { value: 20, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "REALIDAD TECNOLOGICA NACIONAL",
        code: "EICI247-08",
        credits: [{ label: "SCT", value: 2 }],
        flow: [],
        requisites: ["INFO264-00", "INFO272-00", "INFO281-08"],
        historicDistribution: [
          { value: 0, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 0, min: 4, max: 5 },
          { value: 1, min: 5, max: 6 },
          { value: 0, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "SIMULACION",
        code: "INFO274-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO173-00"],
        historicDistribution: [
          { value: 2, min: 1, max: 2 },
          { value: 2, min: 2, max: 3 },
          { value: 1, min: 3, max: 4 },
          { value: 35, min: 4, max: 5 },
          { value: 62, min: 5, max: 6 },
          { value: 20, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ESTRATEGIA Y SI",
        code: "EICI261-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["EICI246-08", "INFO276-08"],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "ADMINISTRACION DE TIC",
        code: "EICI255-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["EICI245-08", "EICI246-08", "INFO276-08"],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "ANTEPROYECTO DE TITULO",
        code: "INFO253-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["EICI245-08", "EICI246-08", "INFO276-08"],
        historicDistribution: [
          { value: 1, min: 1, max: 2 },
          { value: 1, min: 2, max: 3 },
          { value: 2, min: 3, max: 4 },
          { value: 0, min: 4, max: 5 },
          { value: 22, min: 5, max: 6 },
          { value: 89, min: 6, max: 7 },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 3",
        code: "ELECT22",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 2",
        code: "ELECT21",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        taken: [],
      },
      {
        name: "PROYECTO DE TITULO",
        code: "EICI298-09",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 21, min: 1, max: 2 },
          { value: 0, min: 2, max: 3 },
          { value: 0, min: 3, max: 4 },
          { value: 0, min: 4, max: 5 },
          { value: 2, min: 5, max: 6 },
          { value: 71, min: 6, max: 7 },
        ],
        taken: [],
      },
    ],
  },
];

export default semesters;
