import { StateCourse } from "../";
import { ICourse } from "../../interfaces";

const semesters: { semester: ICourse[] }[] = [
  {
    semester: [
      {
        name: "ALGEBRA PARA INGENIERIA",
        code: "BAIN017-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["BAIN036-07", "BAIN038-07", "INFO025-08", "BAIN037-07"],
        requisites: [],
        historicDistribution: [
          { value: 892, label: "1-2" },
          { value: 1047, label: "2-3" },
          { value: 1106, label: "3-4" },
          { value: 2305, label: "4-5" },
          { value: 531, label: "5-6" },
          { value: 98, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "CURSADA",
            grade: 2,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 51, label: "1-2" },
              { value: 88, label: "2-3" },
              { value: 82, label: "3-4" },
              { value: 135, label: "4-5" },
              { value: 29, label: "5-6" },
              { value: 12, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 2.7,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 23, label: "1-2" },
              { value: 31, label: "2-3" },
              { value: 34, label: "3-4" },
              { value: 42, label: "4-5" },
              { value: 2, label: "5-6" },
              { value: 1, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 2.6,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 24, label: "1-2" },
              { value: 50, label: "2-3" },
              { value: 90, label: "3-4" },
              { value: 116, label: "4-5" },
              { value: 48, label: "5-6" },
              { value: 18, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "QUIMICA PARA INGENIERIA",
        code: "BAIN019-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO184-08"],
        requisites: [],
        historicDistribution: [
          { value: 444, label: "1-2" },
          { value: 404, label: "2-3" },
          { value: 710, label: "3-4" },
          { value: 2234, label: "4-5" },
          { value: 957, label: "5-6" },
          { value: 253, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 3.8,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 8, label: "1-2" },
              { value: 5, label: "2-3" },
              { value: 28, label: "3-4" },
              { value: 73, label: "4-5" },
              { value: 28, label: "5-6" },
              { value: 4, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3.7,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 81, label: "1-2" },
              { value: 62, label: "2-3" },
              { value: 43, label: "3-4" },
              { value: 95, label: "4-5" },
              { value: 50, label: "5-6" },
              { value: 16, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "EDUCACIÓN FÍSICA Y SALUD",
        code: "DYRE060-90",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 0, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 1, label: "4-5" },
          { value: 2, label: "5-6" },
          { value: 64, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 0,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 0, label: "1-2" },
              { value: 0, label: "2-3" },
              { value: 0, label: "3-4" },
              { value: 1, label: "4-5" },
              { value: 1, label: "5-6" },
              { value: 21, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "INTRODUCCION A LA PROGRAMACION",
        code: "INFO013-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO023-08", "INFO043-07"],
        requisites: [],
        historicDistribution: [
          { value: 97, label: "1-2" },
          { value: 97, label: "2-3" },
          { value: 109, label: "3-4" },
          { value: 338, label: "4-5" },
          { value: 114, label: "5-6" },
          { value: 31, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 4.3,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 1, label: "1-2" },
              { value: 1, label: "2-3" },
              { value: 1, label: "3-4" },
              { value: 9, label: "4-5" },
              { value: 1, label: "5-6" },
              { value: 0, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3.3,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 1, label: "1-2" },
              { value: 3, label: "2-3" },
              { value: 12, label: "3-4" },
              { value: 38, label: "4-5" },
              { value: 4, label: "5-6" },
              { value: 4, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "TALLER DE INGENIERIA I",
        code: "INFO015-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO025-08"],
        requisites: [],
        historicDistribution: [
          { value: 21, label: "1-2" },
          { value: 11, label: "2-3" },
          { value: 32, label: "3-4" },
          { value: 226, label: "4-5" },
          { value: 205, label: "5-6" },
          { value: 109, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 4.4,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 2, label: "1-2" },
              { value: 0, label: "2-3" },
              { value: 4, label: "3-4" },
              { value: 17, label: "4-5" },
              { value: 17, label: "5-6" },
              { value: 23, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "COMUNICACION: IDIOMA ESPAÑOL",
        code: "BAIN009-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["ADMI100-90"],
        requisites: [],
        historicDistribution: [
          { value: 188, label: "1-2" },
          { value: 73, label: "2-3" },
          { value: 55, label: "3-4" },
          { value: 669, label: "4-5" },
          { value: 1940, label: "5-6" },
          { value: 1209, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 6,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 11, label: "1-2" },
              { value: 5, label: "2-3" },
              { value: 2, label: "3-4" },
              { value: 28, label: "4-5" },
              { value: 183, label: "5-6" },
              { value: 119, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "GEOMETRIA PARA INGENIERIA",
        code: "BAIN012-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["BAIN038-07", "INFO025-08"],
        requisites: [],
        historicDistribution: [
          { value: 1235, label: "1-2" },
          { value: 1010, label: "2-3" },
          { value: 1026, label: "3-4" },
          { value: 2130, label: "4-5" },
          { value: 589, label: "5-6" },
          { value: 132, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "CURSADA",
            grade: 1.8,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 47, label: "1-2" },
              { value: 64, label: "2-3" },
              { value: 95, label: "3-4" },
              { value: 171, label: "4-5" },
              { value: 46, label: "5-6" },
              { value: 11, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 2.2,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 21, label: "1-2" },
              { value: 44, label: "2-3" },
              { value: 25, label: "3-4" },
              { value: 56, label: "4-5" },
              { value: 6, label: "5-6" },
              { value: 0, label: "6-7" },
            ],
            parallelGroup: 0,
          },
          {
            term: "First",
            year: 2008,
            registration: "CURSADA",
            grade: 3,
            state: StateCourse.Failed,
            currentDistribution: [
              { value: 41, label: "1-2" },
              { value: 91, label: "2-3" },
              { value: 81, label: "3-4" },
              { value: 90, label: "4-5" },
              { value: 31, label: "5-6" },
              { value: 7, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
    ],
  },
  {
    semester: [
      {
        name: "ALGEBRA LINEAL PARA INGENIERIA",
        code: "BAIN036-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO043-07", "BAIN052-07", "INFO172-00"],
        requisites: ["BAIN017-07"],
        historicDistribution: [
          { value: 518, label: "1-2" },
          { value: 731, label: "2-3" },
          { value: 738, label: "3-4" },
          { value: 1823, label: "4-5" },
          { value: 308, label: "5-6" },
          { value: 69, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "FISICA I PARA INGENIERIA",
        code: "BAIN038-07",
        credits: [{ label: "SCT", value: 8 }],
        flow: ["BAIN043-07", "INFO184-08"],
        requisites: ["BAIN012-07", "BAIN017-07"],
        historicDistribution: [
          { value: 468, label: "1-2" },
          { value: 657, label: "2-3" },
          { value: 887, label: "3-4" },
          { value: 2033, label: "4-5" },
          { value: 178, label: "5-6" },
          { value: 17, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "COMUNICACION: IDIOMA INGLES",
        code: "BAIN039-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 316, label: "1-2" },
          { value: 156, label: "2-3" },
          { value: 316, label: "3-4" },
          { value: 1608, label: "4-5" },
          { value: 925, label: "5-6" },
          { value: 486, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "Second",
            year: 2008,
            registration: "CURSADA",
            grade: 4,
            state: StateCourse.Passed,
            currentDistribution: [
              { value: 6, label: "1-2" },
              { value: 6, label: "2-3" },
              { value: 24, label: "3-4" },
              { value: 65, label: "4-5" },
              { value: 63, label: "5-6" },
              { value: 30, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "PROGRAMACION",
        code: "INFO023-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO033-07"],
        requisites: ["INFO013-07"],
        historicDistribution: [
          { value: 62, label: "1-2" },
          { value: 61, label: "2-3" },
          { value: 48, label: "3-4" },
          { value: 278, label: "4-5" },
          { value: 74, label: "5-6" },
          { value: 32, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [
          {
            term: "First",
            year: 2009,
            registration: "ANULADA",
            grade: 0,
            state: StateCourse.Canceled,
            currentDistribution: [
              { value: 3, label: "1-2" },
              { value: 0, label: "2-3" },
              { value: 1, label: "3-4" },
              { value: 17, label: "4-5" },
              { value: 5, label: "5-6" },
              { value: 1, label: "6-7" },
            ],
            parallelGroup: 0,
          },
        ],
      },
      {
        name: "TALLER DE INGENIERIA II",
        code: "INFO025-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO035-08"],
        requisites: ["BAIN012-07", "BAIN017-07", "INFO015-08"],
        historicDistribution: [
          { value: 12, label: "1-2" },
          { value: 3, label: "2-3" },
          { value: 5, label: "3-4" },
          { value: 83, label: "4-5" },
          { value: 174, label: "5-6" },
          { value: 110, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "CALCULO I PARA INGENIERIA",
        code: "BAIN037-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["BAIN041-07", "BAIN043-07", "BAIN042-07", "INFO184-08"],
        requisites: ["BAIN017-07"],
        historicDistribution: [
          { value: 611, label: "1-2" },
          { value: 937, label: "2-3" },
          { value: 989, label: "3-4" },
          { value: 1889, label: "4-5" },
          { value: 258, label: "5-6" },
          { value: 30, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ECUACIONES DIFERENCIALES PARA INGENIERIA",
        code: "BAIN041-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["BAIN054-07", "INFO045-08", "BAIN053-07", "INFO183-00"],
        requisites: ["BAIN037-07"],
        historicDistribution: [
          { value: 294, label: "1-2" },
          { value: 392, label: "2-3" },
          { value: 550, label: "3-4" },
          { value: 1457, label: "4-5" },
          { value: 209, label: "5-6" },
          { value: 30, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "FISICA II PARA INGENIERIA",
        code: "BAIN043-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN037-07", "BAIN038-07"],
        historicDistribution: [
          { value: 111, label: "1-2" },
          { value: 190, label: "2-3" },
          { value: 563, label: "3-4" },
          { value: 1603, label: "4-5" },
          { value: 149, label: "5-6" },
          { value: 16, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "PROGRAMACION ORIENTADA A OBJETOS",
        code: "INFO033-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO023-08"],
        historicDistribution: [
          { value: 34, label: "1-2" },
          { value: 20, label: "2-3" },
          { value: 35, label: "3-4" },
          { value: 184, label: "4-5" },
          { value: 81, label: "5-6" },
          { value: 56, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER DE INGENIERIA III",
        code: "INFO035-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: [
          "INFO045-08",
          "INFO053-07",
          "ADMI100-90",
          "INFO175-08",
          "INFO265-08",
          "IECO102-05",
          "INFO264-00",
        ],
        requisites: ["INFO025-08"],
        historicDistribution: [
          { value: 2, label: "1-2" },
          { value: 3, label: "2-3" },
          { value: 9, label: "3-4" },
          { value: 80, label: "4-5" },
          { value: 177, label: "5-6" },
          { value: 36, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ESTRUCTURAS DISCRETAS",
        code: "INFO043-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO053-07"],
        requisites: ["BAIN036-07", "INFO013-07"],
        historicDistribution: [
          { value: 25, label: "1-2" },
          { value: 27, label: "2-3" },
          { value: 70, label: "3-4" },
          { value: 208, label: "4-5" },
          { value: 41, label: "5-6" },
          { value: 6, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "CALCULO II PARA INGENIERIA",
        code: "BAIN042-07",
        credits: [{ label: "SCT", value: 5 }],
        flow: [
          "BAIN054-07",
          "INFO045-08",
          "INFO173-00",
          "IECO102-05",
          "INFO185-97",
        ],
        requisites: ["BAIN037-07"],
        historicDistribution: [
          { value: 397, label: "1-2" },
          { value: 648, label: "2-3" },
          { value: 625, label: "3-4" },
          { value: 1395, label: "4-5" },
          { value: 148, label: "5-6" },
          { value: 27, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ESTADISTICA Y PROBABILIDADES PARA INGENIERIA",
        code: "BAIN052-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO173-00", "INFO185-97"],
        requisites: ["BAIN036-07"],
        historicDistribution: [
          { value: 284, label: "1-2" },
          { value: 174, label: "2-3" },
          { value: 186, label: "3-4" },
          { value: 1306, label: "4-5" },
          { value: 300, label: "5-6" },
          { value: 62, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "FISICA III PARA INGENIERIA",
        code: "BAIN054-07",
        credits: [{ label: "SCT", value: 8 }],
        flow: ["INFO284-08"],
        requisites: ["BAIN041-07", "BAIN042-07"],
        historicDistribution: [
          { value: 54, label: "1-2" },
          { value: 79, label: "2-3" },
          { value: 238, label: "3-4" },
          { value: 1233, label: "4-5" },
          { value: 169, label: "5-6" },
          { value: 12, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO 1",
        code: "ELECT01",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER",
        code: "INFO045-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN041-07", "BAIN042-07", "INFO035-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 30, label: "4-5" },
          { value: 96, label: "5-6" },
          { value: 114, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ESTRUCTURAS DE DATOS Y ALGORITMOS",
        code: "INFO053-07",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO164-00", "INFO175-08", "INFO265-08", "INFO163-08"],
        requisites: ["INFO035-08", "INFO043-07"],
        historicDistribution: [
          { value: 27, label: "1-2" },
          { value: 42, label: "2-3" },
          { value: 76, label: "3-4" },
          { value: 153, label: "4-5" },
          { value: 59, label: "5-6" },
          { value: 6, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "METODOS NUMERICOS PARA INGENIERIA",
        code: "BAIN053-07",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO189-08"],
        requisites: ["BAIN041-07"],
        historicDistribution: [
          { value: 158, label: "1-2" },
          { value: 307, label: "2-3" },
          { value: 498, label: "3-4" },
          { value: 1195, label: "4-5" },
          { value: 149, label: "5-6" },
          { value: 15, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ADMINISTRACION DE EMPRESAS",
        code: "ADMI100-90",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO263-08", "INFO271-08", "INFO275-08", "INFO276-08"],
        requisites: ["BAIN009-07", "INFO035-08"],
        historicDistribution: [
          { value: 9, label: "1-2" },
          { value: 9, label: "2-3" },
          { value: 17, label: "3-4" },
          { value: 246, label: "4-5" },
          { value: 197, label: "5-6" },
          { value: 71, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TEORIA DE AUTOMATAS",
        code: "INFO164-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO261-08", "INFO165-00", "INFO270-00"],
        requisites: ["INFO053-07"],
        historicDistribution: [
          { value: 4, label: "1-2" },
          { value: 23, label: "2-3" },
          { value: 31, label: "3-4" },
          { value: 95, label: "4-5" },
          { value: 63, label: "5-6" },
          { value: 17, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "INVESTIGACION OPERATIVA I",
        code: "INFO172-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO173-00"],
        requisites: ["BAIN036-07"],
        historicDistribution: [
          { value: 20, label: "1-2" },
          { value: 18, label: "2-3" },
          { value: 27, label: "3-4" },
          { value: 106, label: "4-5" },
          { value: 74, label: "5-6" },
          { value: 32, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER DE CONSTRUCCION DE SOFTWARE",
        code: "INFO175-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO263-08", "INFO284-08", "INFO267-00"],
        requisites: ["INFO035-08", "INFO053-07"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 5, label: "3-4" },
          { value: 37, label: "4-5" },
          { value: 90, label: "5-6" },
          { value: 69, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ARQUITECTURA DE COMPUTADORES",
        code: "INFO184-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO183-00", "INFO185-97"],
        requisites: ["BAIN019-07", "BAIN037-07", "BAIN038-07"],
        historicDistribution: [
          { value: 17, label: "1-2" },
          { value: 23, label: "2-3" },
          { value: 33, label: "3-4" },
          { value: 122, label: "4-5" },
          { value: 62, label: "5-6" },
          { value: 12, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "COMPUTACION GRAFICA",
        code: "INFO265-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["INFO035-08", "INFO053-07"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 4, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 62, label: "4-5" },
          { value: 94, label: "5-6" },
          { value: 33, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "BASES DE DATOS",
        code: "INFO261-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO264-00"],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 7, label: "2-3" },
          { value: 20, label: "3-4" },
          { value: 81, label: "4-5" },
          { value: 78, label: "5-6" },
          { value: 21, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ANALISIS DE SISTEMAS LINEALES",
        code: "INFO183-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO189-08", "INFO284-08"],
        requisites: ["BAIN041-07", "INFO184-08"],
        historicDistribution: [
          { value: 12, label: "1-2" },
          { value: 21, label: "2-3" },
          { value: 31, label: "3-4" },
          { value: 121, label: "4-5" },
          { value: 42, label: "5-6" },
          { value: 8, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "INVESTIGACION OPERATIVA II",
        code: "INFO173-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO272-00", "INFO273-00", "INFO274-00"],
        requisites: ["BAIN042-07", "BAIN052-07", "INFO172-00"],
        historicDistribution: [
          { value: 11, label: "1-2" },
          { value: 7, label: "2-3" },
          { value: 26, label: "3-4" },
          { value: 97, label: "4-5" },
          { value: 63, label: "5-6" },
          { value: 20, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "COMPILADORES",
        code: "INFO165-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: [],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 3, label: "1-2" },
          { value: 8, label: "2-3" },
          { value: 35, label: "3-4" },
          { value: 79, label: "4-5" },
          { value: 62, label: "5-6" },
          { value: 19, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "PROGRAMACION CONCURRENTE",
        code: "INFO163-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO182-00"],
        requisites: ["INFO053-07"],
        historicDistribution: [
          { value: 15, label: "1-2" },
          { value: 6, label: "2-3" },
          { value: 18, label: "3-4" },
          { value: 97, label: "4-5" },
          { value: 71, label: "5-6" },
          { value: 14, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "SISTEMA OPERATIVO",
        code: "INFO182-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO281-08", "INFO273-00"],
        requisites: ["INFO163-08"],
        historicDistribution: [
          { value: 5, label: "1-2" },
          { value: 14, label: "2-3" },
          { value: 23, label: "3-4" },
          { value: 96, label: "4-5" },
          { value: 43, label: "5-6" },
          { value: 11, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ECONOMIA GENERAL",
        code: "IECO102-05",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO271-08", "INFO272-00"],
        requisites: ["BAIN042-07", "INFO035-08"],
        historicDistribution: [
          { value: 52, label: "1-2" },
          { value: 57, label: "2-3" },
          { value: 57, label: "3-4" },
          { value: 775, label: "4-5" },
          { value: 365, label: "5-6" },
          { value: 71, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "COMUNICACIONES",
        code: "INFO185-97",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["INFO281-08"],
        requisites: ["BAIN042-07", "BAIN052-07", "INFO184-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 6, label: "3-4" },
          { value: 95, label: "4-5" },
          { value: 48, label: "5-6" },
          { value: 7, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SOFTWARE DE INGENIERIA",
        code: "INFO189-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["EICI245-08"],
        requisites: ["BAIN043-07", "BAIN053-07", "INFO045-08", "INFO183-00"],
        historicDistribution: [
          { value: 12, label: "1-2" },
          { value: 7, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 40, label: "4-5" },
          { value: 69, label: "5-6" },
          { value: 31, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "FUNDAMENTOS DE INGENIERIA DE SOFTWARE",
        code: "INFO263-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["INFO266-08", "INFO264-00"],
        requisites: ["ADMI100-90", "INFO175-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 3, label: "2-3" },
          { value: 10, label: "3-4" },
          { value: 67, label: "4-5" },
          { value: 65, label: "5-6" },
          { value: 15, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "INGENIERIA DE SISTEMAS",
        code: "INFO270-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO271-08", "INFO275-08", "INFO276-08"],
        requisites: ["INFO164-00"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 17, label: "3-4" },
          { value: 63, label: "4-5" },
          { value: 60, label: "5-6" },
          { value: 14, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "INTERFAZ HUMANO - COMPUTADOR",
        code: "INFO266-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI297-90", "EICI245-08"],
        requisites: ["INFO263-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 4, label: "3-4" },
          { value: 42, label: "4-5" },
          { value: 88, label: "5-6" },
          { value: 11, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER INGENIERIA DE SOFTWARE",
        code: "INFO264-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: [
          "INFO268-00",
          "INFO251-08",
          "INFO252-97",
          "EICI297-90",
          "EICI245-08",
          "EICI246-08",
          "EICI247-08",
        ],
        requisites: ["INFO035-08", "INFO261-08", "INFO263-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 8, label: "4-5" },
          { value: 40, label: "5-6" },
          { value: 92, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE INFORMACION",
        code: "INFO271-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["INFO252-97", "EICI297-90", "EICI246-08"],
        requisites: ["ADMI100-90", "IECO102-05", "INFO270-00"],
        historicDistribution: [
          { value: 3, label: "1-2" },
          { value: 3, label: "2-3" },
          { value: 6, label: "3-4" },
          { value: 59, label: "4-5" },
          { value: 77, label: "5-6" },
          { value: 6, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "INGENIERIA ECONOMICA",
        code: "INFO272-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [
          "INFO251-08",
          "INFO252-97",
          "INFO275-08",
          "EICI297-90",
          "INFO276-08",
          "EICI247-08",
        ],
        requisites: ["IECO102-05", "INFO173-00"],
        historicDistribution: [
          { value: 5, label: "1-2" },
          { value: 8, label: "2-3" },
          { value: 11, label: "3-4" },
          { value: 59, label: "4-5" },
          { value: 70, label: "5-6" },
          { value: 16, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "REDES",
        code: "INFO281-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [
          "INFO273-00",
          "INFO251-08",
          "EICI297-90",
          "EICI245-08",
          "EICI246-08",
          "EICI247-08",
        ],
        requisites: ["INFO182-00", "INFO185-97"],
        historicDistribution: [
          { value: 5, label: "1-2" },
          { value: 7, label: "2-3" },
          { value: 10, label: "3-4" },
          { value: 112, label: "4-5" },
          { value: 30, label: "5-6" },
          { value: 2, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER DE INTEGRACION DE TIC",
        code: "INFO284-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI297-90", "EICI245-08", "EICI246-08"],
        requisites: ["BAIN054-07", "INFO175-08", "INFO183-00"],
        historicDistribution: [
          { value: 2, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 9, label: "4-5" },
          { value: 49, label: "5-6" },
          { value: 86, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "TALLER DE BASE DE DATOS",
        code: "INFO268-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO264-00"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 35, label: "4-5" },
          { value: 53, label: "5-6" },
          { value: 34, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "EVALUACION DE DESEMPEÑO",
        code: "INFO273-00",
        credits: [{ label: "SCT", value: 5 }],
        flow: [],
        requisites: ["INFO173-00", "INFO182-00", "INFO281-08"],
        historicDistribution: [
          { value: 0, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 22, label: "4-5" },
          { value: 60, label: "5-6" },
          { value: 34, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SEMINARIO DE ETICA PROFESIONAL",
        code: "INFO251-08",
        credits: [{ label: "SCT", value: 2 }],
        flow: [],
        requisites: ["INFO264-00", "INFO272-00", "INFO281-08"],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "PROYECTO I",
        code: "INFO252-97",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO264-00", "INFO271-08", "INFO272-00"],
        historicDistribution: [
          { value: 0, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 23, label: "4-5" },
          { value: 67, label: "5-6" },
          { value: 28, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE GESTION ESTRATEGICOS",
        code: "INFO275-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["EICI246-08"],
        requisites: ["ADMI100-90", "INFO270-00", "INFO272-00"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 56, label: "4-5" },
          { value: 53, label: "5-6" },
          { value: 6, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "INGLES FUNCIONAL",
        code: "CIDI108-02",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 2, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 29, label: "4-5" },
          { value: 47, label: "5-6" },
          { value: 44, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "PRACTICA PROFESIONAL",
        code: "EICI297-90",
        credits: [{ label: "SCT", value: 8 }],
        flow: [],
        requisites: [
          "INFO264-00",
          "INFO266-08",
          "INFO271-08",
          "INFO272-00",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 1",
        code: "ELECT20",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "INTELIGENCIA ARTIFICIAL",
        code: "INFO267-00",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["INFO175-08"],
        historicDistribution: [
          { value: 5, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 5, label: "3-4" },
          { value: 34, label: "4-5" },
          { value: 65, label: "5-6" },
          { value: 16, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SISTEMAS DE GESTION TACTICOS",
        code: "INFO276-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: ["EICI261-08", "EICI255-08", "INFO253-08"],
        requisites: ["ADMI100-90", "INFO270-00", "INFO272-00"],
        historicDistribution: [
          { value: 0, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 18, label: "4-5" },
          { value: 63, label: "5-6" },
          { value: 34, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "TALLER DE SOFTWARE- PROYECTO INTEGRACIÓN DE TIC",
        code: "EICI245-08",
        credits: [{ label: "SCT", value: 5 }],
        flow: ["EICI255-08", "INFO253-08"],
        requisites: [
          "INFO189-08",
          "INFO264-00",
          "INFO266-08",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 0, label: "4-5" },
          { value: 4, label: "5-6" },
          { value: 33, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ARQUITECTURA DE SISTEMAS",
        code: "EICI246-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: ["EICI261-08", "EICI255-08", "INFO253-08"],
        requisites: [
          "INFO264-00",
          "INFO271-08",
          "INFO275-08",
          "INFO281-08",
          "INFO284-08",
        ],
        historicDistribution: [
          { value: 2, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 3, label: "4-5" },
          { value: 15, label: "5-6" },
          { value: 20, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "REALIDAD TECNOLOGICA NACIONAL",
        code: "EICI247-08",
        credits: [{ label: "SCT", value: 2 }],
        flow: [],
        requisites: ["INFO264-00", "INFO272-00", "INFO281-08"],
        historicDistribution: [
          { value: 0, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 0, label: "4-5" },
          { value: 1, label: "5-6" },
          { value: 0, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "SIMULACION",
        code: "INFO274-00",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["INFO173-00"],
        historicDistribution: [
          { value: 2, label: "1-2" },
          { value: 2, label: "2-3" },
          { value: 1, label: "3-4" },
          { value: 35, label: "4-5" },
          { value: 62, label: "5-6" },
          { value: 20, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
  {
    semester: [
      {
        name: "ESTRATEGIA Y SI",
        code: "EICI261-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["EICI246-08", "INFO276-08"],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ADMINISTRACION DE TIC",
        code: "EICI255-08",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: ["EICI245-08", "EICI246-08", "INFO276-08"],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "ANTEPROYECTO DE TITULO",
        code: "INFO253-08",
        credits: [{ label: "SCT", value: 4 }],
        flow: [],
        requisites: ["EICI245-08", "EICI246-08", "INFO276-08"],
        historicDistribution: [
          { value: 1, label: "1-2" },
          { value: 1, label: "2-3" },
          { value: 2, label: "3-4" },
          { value: 0, label: "4-5" },
          { value: 22, label: "5-6" },
          { value: 89, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 3",
        code: "ELECT22",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "OPTATIVO PROFESIONAL 2",
        code: "ELECT21",
        credits: [{ label: "SCT", value: 0 }],
        flow: [],
        requisites: [],
        historicDistribution: [],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
      {
        name: "PROYECTO DE TITULO",
        code: "EICI298-09",
        credits: [{ label: "SCT", value: 6 }],
        flow: [],
        requisites: [],
        historicDistribution: [
          { value: 21, label: "1-2" },
          { value: 0, label: "2-3" },
          { value: 0, label: "3-4" },
          { value: 0, label: "4-5" },
          { value: 2, label: "5-6" },
          { value: 71, label: "6-7" },
        ],
        bandColors: [
          {
            min: 1,
            max: 3.4999,
            color: "#d6604d",
          },
          {
            min: 3.5,
            max: 3.9999,
            color: "#f48873",
          },
          {
            min: 4,
            max: 4.4999,
            color: "#a7dc78",
          },
          {
            min: 4.5,
            max: 7,
            color: "#66b43e",
          },
        ],
        taken: [],
      },
    ],
  },
];

export default semesters;
